/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace AlephNote.Plugins.Evernote.EDAM.Type
{
  public enum BusinessUserRole
  {
    ADMIN = 1,
    NORMAL = 2,
  }
}
