/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace AlephNote.Plugins.Evernote.EDAM.Type
{
  public class Constants
  {
    public static string CLASSIFICATION_RECIPE_USER_NON_RECIPE = "000";
    public static string CLASSIFICATION_RECIPE_USER_RECIPE = "001";
    public static string CLASSIFICATION_RECIPE_SERVICE_RECIPE = "002";
    public static string EDAM_NOTE_SOURCE_WEB_CLIP = "web.clip";
    public static string EDAM_NOTE_SOURCE_MAIL_CLIP = "mail.clip";
    public static string EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY = "mail.smtp";
  }
}
