/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace AlephNote.Plugins.Evernote.EDAM.Type
{
  public enum PremiumOrderStatus
  {
    NONE = 0,
    PENDING = 1,
    ACTIVE = 2,
    FAILED = 3,
    CANCELLATION_PENDING = 4,
    CANCELED = 5,
  }
}
