/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace AlephNote.Plugins.Evernote.EDAM.Type
{
  public enum ReminderEmailConfig
  {
    DO_NOT_SEND = 1,
    SEND_DAILY_EMAIL = 2,
  }
}
