/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

using System;
using System.Text;
using AlephNote.Plugins.Evernote.Thrift.Protocol;

namespace AlephNote.Plugins.Evernote.EDAM.Type
{

  #if !SILVERLIGHT && !NETFX_CORE
  [Serializable]
  #endif
  public partial class SharedNotebookRecipientSettings : TBase
  {
    private bool _reminderNotifyEmail;
    private bool _reminderNotifyInApp;

    public bool ReminderNotifyEmail
    {
      get
      {
        return _reminderNotifyEmail;
      }
      set
      {
        __isset.reminderNotifyEmail = true;
        this._reminderNotifyEmail = value;
      }
    }

    public bool ReminderNotifyInApp
    {
      get
      {
        return _reminderNotifyInApp;
      }
      set
      {
        __isset.reminderNotifyInApp = true;
        this._reminderNotifyInApp = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT && !NETFX_CORE
    [Serializable]
    #endif
    public struct Isset {
      public bool reminderNotifyEmail;
      public bool reminderNotifyInApp;
    }

    public SharedNotebookRecipientSettings() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Bool) {
              ReminderNotifyEmail = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Bool) {
              ReminderNotifyInApp = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SharedNotebookRecipientSettings");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.reminderNotifyEmail) {
        field.Name = "reminderNotifyEmail";
        field.Type = TType.Bool;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(ReminderNotifyEmail);
        oprot.WriteFieldEnd();
      }
      if (__isset.reminderNotifyInApp) {
        field.Name = "reminderNotifyInApp";
        field.Type = TType.Bool;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(ReminderNotifyInApp);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SharedNotebookRecipientSettings(");
      sb.Append("ReminderNotifyEmail: ");
      sb.Append(ReminderNotifyEmail);
      sb.Append(",ReminderNotifyInApp: ");
      sb.Append(ReminderNotifyInApp);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
