/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace AlephNote.Plugins.Evernote.EDAM.Type
{
  public enum SharedNotebookPrivilegeLevel
  {
    READ_NOTEBOOK = 0,
    MODIFY_NOTEBOOK_PLUS_ACTIVITY = 1,
    READ_NOTEBOOK_PLUS_ACTIVITY = 2,
    GROUP = 3,
    FULL_ACCESS = 4,
    BUSINESS_FULL_ACCESS = 5,
  }
}
