/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace AlephNote.Plugins.Evernote.EDAM.Type
{
  public enum SharedNotebookInstanceRestrictions
  {
    ONLY_JOINED_OR_PREVIEW = 1,
    NO_SHARED_NOTEBOOKS = 2,
  }
}
