/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace AlephNote.Plugins.Evernote.EDAM.Type
{
  public enum SponsoredGroupRole
  {
    GROUP_MEMBER = 1,
    GROUP_ADMIN = 2,
    GROUP_OWNER = 3,
  }
}
