/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace AlephNote.Plugins.Evernote.EDAM.UserStore
{
  public class Constants
  {
    public static short EDAM_VERSION_MAJOR = 1;
    public static short EDAM_VERSION_MINOR = 25;
  }
}
