/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

using System;
using System.Collections.Generic;
using System.Text;
using AlephNote.Plugins.Evernote.Thrift.Protocol;

namespace AlephNote.Plugins.Evernote.EDAM.NoteStore
{

  #if !SILVERLIGHT && !NETFX_CORE
  [Serializable]
  #endif
  public partial class NotesMetadataList : TBase
  {
    private int _startIndex;
    private int _totalNotes;
    private List<NoteMetadata> _notes;
    private List<string> _stoppedWords;
    private List<string> _searchedWords;
    private int _updateCount;

    public int StartIndex
    {
      get
      {
        return _startIndex;
      }
      set
      {
        __isset.startIndex = true;
        this._startIndex = value;
      }
    }

    public int TotalNotes
    {
      get
      {
        return _totalNotes;
      }
      set
      {
        __isset.totalNotes = true;
        this._totalNotes = value;
      }
    }

    public List<NoteMetadata> Notes
    {
      get
      {
        return _notes;
      }
      set
      {
        __isset.notes = true;
        this._notes = value;
      }
    }

    public List<string> StoppedWords
    {
      get
      {
        return _stoppedWords;
      }
      set
      {
        __isset.stoppedWords = true;
        this._stoppedWords = value;
      }
    }

    public List<string> SearchedWords
    {
      get
      {
        return _searchedWords;
      }
      set
      {
        __isset.searchedWords = true;
        this._searchedWords = value;
      }
    }

    public int UpdateCount
    {
      get
      {
        return _updateCount;
      }
      set
      {
        __isset.updateCount = true;
        this._updateCount = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT && !NETFX_CORE
    [Serializable]
    #endif
    public struct Isset {
      public bool startIndex;
      public bool totalNotes;
      public bool notes;
      public bool stoppedWords;
      public bool searchedWords;
      public bool updateCount;
    }

    public NotesMetadataList() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              StartIndex = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              TotalNotes = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                Notes = new List<NoteMetadata>();
                TList _list64 = iprot.ReadListBegin();
                for( int _i65 = 0; _i65 < _list64.Count; ++_i65)
                {
                  NoteMetadata _elem66 = new NoteMetadata();
                  _elem66 = new NoteMetadata();
                  _elem66.Read(iprot);
                  Notes.Add(_elem66);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.List) {
              {
                StoppedWords = new List<string>();
                TList _list67 = iprot.ReadListBegin();
                for( int _i68 = 0; _i68 < _list67.Count; ++_i68)
                {
                  string _elem69 = null;
                  _elem69 = iprot.ReadString();
                  StoppedWords.Add(_elem69);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.List) {
              {
                SearchedWords = new List<string>();
                TList _list70 = iprot.ReadListBegin();
                for( int _i71 = 0; _i71 < _list70.Count; ++_i71)
                {
                  string _elem72 = null;
                  _elem72 = iprot.ReadString();
                  SearchedWords.Add(_elem72);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I32) {
              UpdateCount = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("NotesMetadataList");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.startIndex) {
        field.Name = "startIndex";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(StartIndex);
        oprot.WriteFieldEnd();
      }
      if (__isset.totalNotes) {
        field.Name = "totalNotes";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(TotalNotes);
        oprot.WriteFieldEnd();
      }
      if (Notes != null && __isset.notes) {
        field.Name = "notes";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Notes.Count));
          foreach (NoteMetadata _iter73 in Notes)
          {
            _iter73.Write(oprot);
            oprot.WriteListEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      if (StoppedWords != null && __isset.stoppedWords) {
        field.Name = "stoppedWords";
        field.Type = TType.List;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, StoppedWords.Count));
          foreach (string _iter74 in StoppedWords)
          {
            oprot.WriteString(_iter74);
            oprot.WriteListEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      if (SearchedWords != null && __isset.searchedWords) {
        field.Name = "searchedWords";
        field.Type = TType.List;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, SearchedWords.Count));
          foreach (string _iter75 in SearchedWords)
          {
            oprot.WriteString(_iter75);
            oprot.WriteListEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.updateCount) {
        field.Name = "updateCount";
        field.Type = TType.I32;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(UpdateCount);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("NotesMetadataList(");
      sb.Append("StartIndex: ");
      sb.Append(StartIndex);
      sb.Append(",TotalNotes: ");
      sb.Append(TotalNotes);
      sb.Append(",Notes: ");
      sb.Append(Notes);
      sb.Append(",StoppedWords: ");
      sb.Append(StoppedWords);
      sb.Append(",SearchedWords: ");
      sb.Append(SearchedWords);
      sb.Append(",UpdateCount: ");
      sb.Append(UpdateCount);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
