//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlephNote.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlephNote.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Accounts]
        ///AlephNote is based around remotes that come from various plugins.
        ///Here you can specify where your notes are synchronized from/to (normally this is a specific server/service).
        ///
        ///Press the (+) Button to add a new remote configuration and select it from the dropdown box.
        ///Then enter your remote-specific configurations.
        ///
        ///The following remotes are provided by default:
        ///
        /// - SimpleNote:   Synchronization with the SimpleNote server
        /// - StandardNote: Synchronization with a StandardFile server
        /// - Ne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpTexts {
            get {
                return ResourceManager.GetString("HelpTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///ac
        ///accumsan
        ///ad
        ///adipiscing
        ///aenean
        ///aliquam
        ///aliquet
        ///amet
        ///ante
        ///aptent
        ///arcu
        ///at
        ///auctor
        ///augue
        ///bibendum
        ///class
        ///commodo
        ///condimentum
        ///congue
        ///consectetur
        ///conubia
        ///convallis
        ///cras
        ///cubilia
        ///curabitur
        ///curae
        ///cursus
        ///dapibus
        ///diam
        ///dictum
        ///dignissim
        ///dolor
        ///donec
        ///dui
        ///duis
        ///efficitur
        ///egestas
        ///eget
        ///eleifend
        ///elementum
        ///elit
        ///enim
        ///erat
        ///eros
        ///est
        ///et
        ///etiam
        ///eu
        ///euismod
        ///ex
        ///fames
        ///faucibus
        ///felis
        ///fermentum
        ///feugiat
        ///finibus
        ///fringilla
        ///gravida
        ///hendrerit
        ///himenaeos
        ///iaculis
        ///id
        ///in
        ///inceptos
        ///in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoremIpsum {
            get {
                return ResourceManager.GetString("LoremIpsum", resourceCulture);
            }
        }
    }
}
