

build:


publish_gitbackupservice:
	cd AlephNote.GitBackupService && dotnet publish --runtime linux-x64 --configuration Release /p:PublishSingleFile=true
	cd AlephNote.GitBackupService && dotnet publish --runtime linux-arm64 --configuration Release /p:PublishSingleFile=true